spring.application.name=portfolio-service
server.port=8080

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# ==========================================
# VIRTUAL THREADS (Java 21)
# ==========================================
spring.threads.virtual.enabled=true

# ==========================================
# GITHUB INTEGRATION
# ==========================================
github.username=${GITHUB_USERNAME:AndreyJVM}

# ==========================================
# ACTUATOR & HEALTHCHECK
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.ru.vorobevaqa=DEBUG
